-- team_invites: team-scoped invitations (separate from platform-level invitations table).
-- accepted = NULL (pending), true (accepted), false (declined).
-- token generated by DB default using pgcrypto (already enabled).

CREATE TABLE team_invites (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id     uuid        NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  email       text        NOT NULL,
  invited_by  uuid        NOT NULL REFERENCES auth.users(id),
  role        text        NOT NULL DEFAULT 'team_member'
                          CHECK (role IN ('org_owner', 'org_admin', 'team_manager', 'team_member', 'viewer')),
  token       text        NOT NULL UNIQUE,
  accepted    boolean     DEFAULT NULL,
  expires_at  timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ON team_invites(team_id);
CREATE INDEX ON team_invites(email);
CREATE INDEX ON team_invites(token);

ALTER TABLE team_invites ENABLE ROW LEVEL SECURITY;

-- Team admins/managers can read invites for their teams
CREATE POLICY "team_invites: team member can read own team invites"
  ON team_invites FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM team_members tm
      WHERE tm.team_id = team_invites.team_id
        AND tm.user_id = auth.uid()
        AND tm.role IN ('org_owner', 'org_admin', 'team_manager')
    )
    OR email = (SELECT email FROM auth.users WHERE id = auth.uid())
  );

-- Managers and above can create invites
CREATE POLICY "team_invites: manager or above can insert"
  ON team_invites FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM team_members tm
      WHERE tm.team_id = team_invites.team_id
        AND tm.user_id = auth.uid()
        AND tm.role IN ('org_owner', 'org_admin', 'team_manager')
    )
  );

-- UPDATE (accept/decline) is service role only — called by accept/decline API routes

-- Inviter or admin can delete/revoke an invite
CREATE POLICY "team_invites: inviter or admin can delete"
  ON team_invites FOR DELETE
  USING (
    invited_by = auth.uid()
    OR is_org_admin_or_owner(
      (SELECT org_id FROM teams WHERE id = team_invites.team_id)
    )
  );
