-- Step 1: New tables — organizations, teams, team_members, permissions,
-- invitations, goal_accounts, budget_daily_snapshots
--
-- No existing tables are modified here. Those changes happen in Steps 2 and 3.
-- budget_daily_snapshots.budget_id has no FK to budgets — deferred to Step 3.
-- goal_accounts RLS uses temporary user_id-only policies — replaced in Step 2
-- once savings_goals gains owner_type and owner_id.
-- pgcrypto already enabled at v1.3 — no CREATE EXTENSION needed.

-- ============================================================
-- TABLES
-- ============================================================

-- 1. organizations
CREATE TABLE organizations (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name       text        NOT NULL CHECK (char_length(name) > 0),
  owner_id   uuid        NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ON organizations(owner_id);

-- 2. teams
CREATE TABLE teams (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id      uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name        text        NOT NULL CHECK (char_length(name) > 0),
  description text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ON teams(org_id);

-- 3. team_members
CREATE TABLE team_members (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id    uuid        NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  user_id    uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role       text        NOT NULL CHECK (role IN ('org_owner','org_admin','team_manager','team_member','personal')),
  joined_at  timestamptz NOT NULL DEFAULT now(),
  invited_by uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
  UNIQUE (team_id, user_id)
);

CREATE INDEX ON team_members(user_id);
CREATE INDEX ON team_members(team_id);

-- 4. permissions
CREATE TABLE permissions (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  role        text        NOT NULL,
  feature_key text        NOT NULL,
  enabled     boolean     NOT NULL DEFAULT true,
  org_id      uuid        REFERENCES organizations(id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE NULLS NOT DISTINCT (role, feature_key, org_id)
);

CREATE INDEX ON permissions(role, feature_key);
CREATE INDEX ON permissions(org_id);

-- 5. invitations
CREATE TABLE invitations (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id     uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  team_id    uuid        REFERENCES teams(id) ON DELETE CASCADE,
  invited_by uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  email      text,
  role       text        NOT NULL CHECK (role IN ('org_admin','team_manager','team_member')),
  -- token is generated by the API route: crypto.randomBytes(32).toString('hex')
  -- No DB DEFAULT — application must supply the token before insert.
  token      text        NOT NULL UNIQUE,
  accepted   boolean     NOT NULL DEFAULT false,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- token index is implicit from UNIQUE
CREATE INDEX ON invitations(org_id);
CREATE INDEX ON invitations(email);

-- 6. goal_accounts
-- Junction table: links Plaid accounts to savings goals.
-- Primary source of truth for spending attribution and balance sync.
CREATE TABLE goal_accounts (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  goal_id          uuid        NOT NULL REFERENCES savings_goals(id) ON DELETE CASCADE,
  user_id          uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  plaid_account_id text        NOT NULL,
  plaid_item_id    text        NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (goal_id, plaid_account_id)
);

CREATE INDEX ON goal_accounts(goal_id);
CREATE INDEX ON goal_accounts(plaid_account_id);
CREATE INDEX ON goal_accounts(user_id);

-- 7. budget_daily_snapshots
-- Immutable daily record written by the nightly cron.
-- budget_id FK to budgets is intentionally omitted — added in Step 3 migration
-- once the rebuilt budgets table exists. No cron runs between Step 1 and Step 3,
-- so no data will be written to this table during that window.
CREATE TABLE budget_daily_snapshots (
  id                   uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  budget_id            uuid         NOT NULL,
  date                 date         NOT NULL,
  daily_rate           numeric(12,2) NOT NULL,
  amount_spent         numeric(12,2) NOT NULL DEFAULT 0,
  remaining_after      numeric(12,2) NOT NULL,
  days_remaining_after integer      NOT NULL,
  created_at           timestamptz  NOT NULL DEFAULT now(),
  UNIQUE (budget_id, date)
);

-- (budget_id, date) index implicit from UNIQUE
CREATE INDEX ON budget_daily_snapshots(date);

-- ============================================================
-- SECURITY DEFINER HELPERS
-- Created after all tables exist. SECURITY DEFINER bypasses RLS
-- so these functions can safely query team_members without
-- triggering recursive policy evaluation.
-- ============================================================

-- Returns all team IDs the current user belongs to.
-- Used in SELECT policies across teams, organizations, and org-owned data.
CREATE OR REPLACE FUNCTION get_my_team_ids()
RETURNS TABLE(team_id uuid)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT team_id FROM team_members WHERE user_id = auth.uid();
$$;

-- Returns true if the current user has org_admin or org_owner role
-- in any team belonging to the given org.
CREATE OR REPLACE FUNCTION is_org_admin_or_owner(p_org_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM team_members tm
    JOIN teams t ON t.id = tm.team_id
    WHERE tm.user_id = auth.uid()
      AND t.org_id = p_org_id
      AND tm.role IN ('org_owner', 'org_admin')
  );
$$;

-- ============================================================
-- RLS — organizations
-- ============================================================

ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "orgs: owner or member can read"
  ON organizations FOR SELECT
  USING (
    auth.uid() = owner_id
    OR EXISTS (
      SELECT 1
      FROM get_my_team_ids() gmt
      JOIN teams t ON t.id = gmt.team_id
      WHERE t.org_id = organizations.id
    )
  );

CREATE POLICY "orgs: any authenticated user can create"
  ON organizations FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "orgs: owner can update"
  ON organizations FOR UPDATE
  USING (auth.uid() = owner_id);

CREATE POLICY "orgs: owner can delete"
  ON organizations FOR DELETE
  USING (auth.uid() = owner_id);

-- ============================================================
-- RLS — teams
-- ============================================================

ALTER TABLE teams ENABLE ROW LEVEL SECURITY;

CREATE POLICY "teams: member or org admin can read"
  ON teams FOR SELECT
  USING (
    EXISTS (SELECT 1 FROM get_my_team_ids() WHERE team_id = teams.id)
    OR is_org_admin_or_owner(teams.org_id)
  );

CREATE POLICY "teams: org admin or owner can insert"
  ON teams FOR INSERT
  WITH CHECK (is_org_admin_or_owner(org_id));

CREATE POLICY "teams: org admin or owner can update"
  ON teams FOR UPDATE
  USING (is_org_admin_or_owner(org_id));

CREATE POLICY "teams: org admin or owner can delete"
  ON teams FOR DELETE
  USING (is_org_admin_or_owner(org_id));

-- ============================================================
-- RLS — team_members
-- ============================================================

ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "team_members: own rows or org admin can read"
  ON team_members FOR SELECT
  USING (
    user_id = auth.uid()
    OR is_org_admin_or_owner(
      (SELECT org_id FROM teams WHERE id = team_members.team_id)
    )
  );

-- Initial org setup (adding the first org_owner row) is done via service role.
-- Subsequent inserts require org_admin, org_owner, or team_manager.
CREATE POLICY "team_members: org admin or owner can insert"
  ON team_members FOR INSERT
  WITH CHECK (
    is_org_admin_or_owner(
      (SELECT org_id FROM teams WHERE id = team_id)
    )
  );

CREATE POLICY "team_members: org admin or owner can update"
  ON team_members FOR UPDATE
  USING (
    is_org_admin_or_owner(
      (SELECT org_id FROM teams WHERE id = team_members.team_id)
    )
  );

CREATE POLICY "team_members: org admin, owner, or self can delete"
  ON team_members FOR DELETE
  USING (
    user_id = auth.uid()
    OR is_org_admin_or_owner(
      (SELECT org_id FROM teams WHERE id = team_members.team_id)
    )
  );

-- ============================================================
-- RLS — permissions
-- ============================================================

ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "permissions: all authenticated users can read"
  ON permissions FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- Seeded defaults are inserted by this migration (service role, bypasses RLS).
-- Org-level overrides can be written by the org owner only.
CREATE POLICY "permissions: org owner can insert org-level override"
  ON permissions FOR INSERT
  WITH CHECK (
    org_id IS NOT NULL
    AND auth.uid() = (SELECT owner_id FROM organizations WHERE id = org_id)
  );

CREATE POLICY "permissions: org owner can update org-level override"
  ON permissions FOR UPDATE
  USING (
    org_id IS NOT NULL
    AND auth.uid() = (SELECT owner_id FROM organizations WHERE id = org_id)
  );

CREATE POLICY "permissions: org owner can delete org-level override"
  ON permissions FOR DELETE
  USING (
    org_id IS NOT NULL
    AND auth.uid() = (SELECT owner_id FROM organizations WHERE id = org_id)
  );

-- ============================================================
-- RLS — invitations
-- ============================================================

ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "invitations: org admin or owner can read"
  ON invitations FOR SELECT
  USING (is_org_admin_or_owner(org_id));

-- team_manager can insert if team_id matches one of their teams.
-- When team_id IS NULL (org-level invite), the EXISTS is false, so only
-- org_admin/org_owner can create org-level invites.
CREATE POLICY "invitations: org admin, owner, or team manager can insert"
  ON invitations FOR INSERT
  WITH CHECK (
    is_org_admin_or_owner(org_id)
    OR EXISTS (
      SELECT 1 FROM team_members tm
      WHERE tm.user_id = auth.uid()
        AND tm.team_id = invitations.team_id
        AND tm.role = 'team_manager'
    )
  );

-- UPDATE (marking accepted = true) is service role only — called by the accept
-- API route. No authenticated UPDATE policy is added here.

CREATE POLICY "invitations: org admin or owner can delete"
  ON invitations FOR DELETE
  USING (is_org_admin_or_owner(org_id));

-- ============================================================
-- RLS — goal_accounts (TEMPORARY — replaced in Step 2)
-- savings_goals does not yet have owner_type or owner_id.
-- Full team/org-aware policies are added in the Step 2 migration
-- once those columns exist on savings_goals.
-- ============================================================

ALTER TABLE goal_accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "goal_accounts: own rows select (temporary, replaced in step 2)"
  ON goal_accounts FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "goal_accounts: own rows insert (temporary, replaced in step 2)"
  ON goal_accounts FOR INSERT
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "goal_accounts: own rows delete (temporary, replaced in step 2)"
  ON goal_accounts FOR DELETE
  USING (user_id = auth.uid());

-- ============================================================
-- RLS — budget_daily_snapshots
-- All writes are service role only (nightly cron).
-- SELECT policy references the new budgets table which doesn't exist yet —
-- added in Step 3. Until then, no authenticated reads (service role reads all).
-- ============================================================

ALTER TABLE budget_daily_snapshots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "snapshots: no authenticated access (service role only)"
  ON budget_daily_snapshots FOR SELECT
  USING (false);

-- No INSERT / UPDATE / DELETE policies for authenticated users.

-- ============================================================
-- SEED — permissions defaults
-- All features enabled for all roles except:
--   personal and team_member: team_budgets=false, invite_by_link=false
-- ============================================================

INSERT INTO permissions (role, feature_key, enabled) VALUES
  -- org_owner: all features on
  ('org_owner', 'quarterly_budgets',  true),
  ('org_owner', 'yearly_budgets',     true),
  ('org_owner', 'goal_contributions', true),
  ('org_owner', 'bulk_actions',       true),
  ('org_owner', 'team_budgets',       true),
  ('org_owner', 'invite_by_link',     true),
  ('org_owner', 'analytics',          true),
  -- org_admin: all features on
  ('org_admin', 'quarterly_budgets',  true),
  ('org_admin', 'yearly_budgets',     true),
  ('org_admin', 'goal_contributions', true),
  ('org_admin', 'bulk_actions',       true),
  ('org_admin', 'team_budgets',       true),
  ('org_admin', 'invite_by_link',     true),
  ('org_admin', 'analytics',          true),
  -- team_manager: all features on
  ('team_manager', 'quarterly_budgets',  true),
  ('team_manager', 'yearly_budgets',     true),
  ('team_manager', 'goal_contributions', true),
  ('team_manager', 'bulk_actions',       true),
  ('team_manager', 'team_budgets',       true),
  ('team_manager', 'invite_by_link',     true),
  ('team_manager', 'analytics',          true),
  -- team_member: read-only role; cannot manage team budgets or send invites
  ('team_member', 'quarterly_budgets',  true),
  ('team_member', 'yearly_budgets',     true),
  ('team_member', 'goal_contributions', true),
  ('team_member', 'bulk_actions',       true),
  ('team_member', 'team_budgets',       false),
  ('team_member', 'invite_by_link',     false),
  ('team_member', 'analytics',          true),
  -- personal: no team context; team_budgets and invite_by_link are not applicable
  ('personal', 'quarterly_budgets',  true),
  ('personal', 'yearly_budgets',     true),
  ('personal', 'goal_contributions', true),
  ('personal', 'bulk_actions',       true),
  ('personal', 'team_budgets',       false),
  ('personal', 'invite_by_link',     false),
  ('personal', 'analytics',          true);
